/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'poirot3' at '10/15/16 3:53 PM' with Gradle 3.1
 *
 * @author poirot3, @date 10/15/16 3:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
